governance:
  - dionysuzx
  - mayushii-nyan
core:
  - dionysuzx
  - mayushii-nyan
erc:
  - dionysuzx
  - mayushii-nyan
networking:
  - dionysuzx
  - mayushii-nyan
interface:
  - dionysuzx
  - mayushii-nyan
meta:
  - dionysuzx
  - mayushii-nyan
informational:
  - dionysuzx
  - mayushii-nyan
